### ISSUE TITLE
[Update] Documentation changes for 2.0.0

### ISSUE THREAD

**Issue by mkindahl** [timescale/docs.timescale.com-content#462]
Add necessary changes to the documentation for 2.0.0.

- [ ] Parameter `cascade_to_materialization` was removed timescale/timescaledb#2137
- [ ] Parameter `cascade` was removed timescale/timescaledb-private#786
- [ ] Chunk policies were renamed timescale/timescaledb#2149
- [ ] Make sure to demonstrate how to use `pg_pretty` since we have removed the prettified columns from the views.
- [ ] Reformulate warning about using replication factor > 1

**Comment by mfreed** [comment]
Issue has been superseded by other issues.
