### ISSUE TITLE
[Update] Multi-node and distributed hypertables

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#492]
**New Intro / Getting Started**

- [x] Introduce single, primary/backup, and multinode configuration in updated intro - https://docs.timescale.com/latest/introduction [@mfreed]
- [x] Create new "quick-start / quick configure" guide to setting up multi-node, new doc for "getting started" section - https://docs.timescale.com/beta-v2.0.0/getting-started/setup-multi-node [@solugebefola][ #525 ]
- [x] Add "quick start" for setting up a new postgres user (simplified for data auth): https://docs.timescale.com/beta-v2.0.0/getting-started/setup-multi-node#data-node-auth [@mkindahl, @solugebefola ][ #525 ]

**New Using Distributed Hypertables**  [@erimatnor]
https://docs.timescale.com/beta-v2.0.0/using-timescaledb/distributed-hypertables

- [x] New intro to section with architectural picture of ANs / DNs and brief description of distributed hypertable [@erimatnor]
- [x] Subsection:  Easy configuration for ANs and DNs, adding data nodes to access node
- [x] Subsection:  Creating distributed hypertable - https://docs.timescale.com/beta-v2.0.0/using-timescaledb/distributed-hypertables#create  [@erimatnor]
- [x] Subsection:  Changing the Number of Data Nodes for a Distributed Hypertable - https://docs.timescale.com/beta-v2.0.0/using-timescaledb/distributed-hypertables#changing-data-nodes  [@erimatnor]
- [x] Subsection: Advanced topic:  Configuring data nodes - https://docs.timescale.com/beta-v2.0.0/getting-started/setup-multi-node#config-data-nodes
- [x] Subsection: Advanced topic: Data authentication:  Edit in light of quick-start, including some instructions about when/if each step needs to be taken https://docs.timescale.com/beta-v2.0.0/getting-started/setup-multi-node#data-node-auth [ @solugebefola  ][ #525 ]
- [x] Subsection: Current Status and Limitations (see below)
- ? Advanced topic: Schedule transaction cleanup (e.g., via custom job): https://github.com/timescale/timescaledb-private/issues/545 [ @pmwkaa ]

**Current Status and Limitations**
- [x] Describe consistency model: https://github.com/timescale/timescaledb-private/issues/514
- [x] Roles and permissions management
- [x] Compression (only `compress_chunk`, no policies) [@gayyappan ]
- [x] Continuous Aggs (currently blocked)     [@gayyappan]
- [x] Data retention policies   [@gayyappan] This works on distributed hypertables.
- [x] Custom jobs [@gayyappan]
- [x] How do relational tables + JOINs work?  [@gayyappan] already listed under Limitations section.
- [x] Replication and HA  [@gayyappan] We have docs for this. Added link to limitations section.
- [x] Backup and recovery https://github.com/timescale/timescaledb-private/issues/516 [@gayyappan]
- [x] UDFs https://github.com/timescale/timescaledb-private/issues/469 [ @gayyappan ]

**API docs**  (@pmwkaa)

- [x] Review `create_distributed_hypertable` [ @k-rus ] [ #533 ]
- [x] Review `add_data_node` - Improper layout as syntax/arguments should be at top [ @pmwkaa ] [ #541 ]
- [x] Review `delete_data_node` (no changes required)
- [x] Review `attach_data_node` (no changes required)
- [x] Review `detach_data_node` [ @pmwkaa ][ #529 ]
- [x] Review `distributed_exec` [ @k-rus ] [ #569 ]
- [x] Review `set_replication_factor` https://docs.timescale.com/beta-v2.0.0/api#set_replication_factor [ @k-rus ]
- [x] Remove `allow_new_chunks` (was moved to internal namespace)
- [x] Remove `block_new_chunks` (was moved to internal namespace)
- ~Add label/badge to all multi-node functions~

**Misc**
- [x] Document multinode-specific GUCs. For instance `timescaledb.remote_data_fetcher` can be set to `row-by-row` and `cursor`, where the former is the default since the latter doesn't support parallel execution on the DN. [ @mkindahl @ryanbooz ]
- [x] Reformulate warning about using replication factor > 1 [ @k-rus  ]
- [x] Remove/reformulate warnings about using space partitioning https://github.com/timescale/timescaledb-private/issues/525 [ @k-rus ] [ #564 ]

**Comment by mfreed** [comment]
Let's talk about the "current status and limitation", as well as how we plan to include.  I do worry a bit about that sometimes we try to be _very complete_, so we end up writing a _lot_ and users end up not reading because it's just too length / in the weeds.

**Comment by solugebefola** [comment]
For "Add "quick start" for setting up a new postgres user", I'm not quite sure what that's supposed to encompass vs. the overall "Create new "quick-start / quick configure" guide to setting up multi-node" changes to `getting-started/setup-multinode`?  @mfreed

**Comment by mfreed** [comment]
@solugebefola I'll just review when you are done.  The old instructions just had a /lot/ of details about adding new databases users (and then propagating user creation to DNs as well), certification authentication approach, etc.  Was thinking there was a way to just show one simplified perferred approach, rather than multiple.     But let's review your draft and see what's needed.

**Comment by solugebefola** [comment]
@mfreed done and up for review #525

**Comment by mfreed** [comment]
* Making separate issue for annotating API functions with :single-node: or :multi-node: -https://github.com/timescale/docs.timescale.com-content/issues/574
* Issue "Advanced topic: Schedule transaction cleanup (e.g., via custom job)" delayed until product feature finalized @pmwkaa ]

**Comment by solugebefola** [comment]
bump?  Seems like there is only "introduction" changes to add?

**Comment by solugebefola** [comment]
@mfreed close?
